const mongoose = require('mongoose');

let Schema = new mongoose.Schema({
    serverID: String,
    serverName: String,
    serverIp: String,
    cfxCode: String,
    ts3Ip: String,
    ts3Port: String,
    ts3Kanal: String,
    launcherKanal: String,
    rollogalma: String,
    rollogverme: String,
    aktifresmi: String,
    bakimresim: String,
    restartresim: String,
    discorddavet: String,
    yetkilirol: String,
    developerrol: String,
    rolyetkilisi: String,
    destekyetklirol: String,
    kayityetkilirol: String,
    gelengidenkanal: String,
    otorolkanal: String,
    guvenliklog: String,
    modlog: String,
    seslog: String,
    kufurlog: String,
    reklamlog: String,
    ticketlog: String,
    davetlog: String,
    icyetkili: String,
    lasticket: Number,
    ticketkategori: String,
    kayitodasi: String,
    destekodasi: String,
    otorol: String,
})

module.exports = mongoose.model('servers', Schema)